2023 03 14
zingolabs/zingo-mobile pull request #241
Opened 2023-03-15 01:11 UTC by fluidvanadium

in this branch, i modified the qrcodescanner to correctly display in android. unfortunately, i am unable to test ios...

also enabled the pixelometer in the dev environment only

2023-03-15 02:53 UTC, fluidvanadium commented
oops, now yarn testing -u

2023-03-15 19:15 UTC, juanky201271 commented
@fluidvanadium can you added here a couple of screenshots with before & after of this PR. I'm asking because in my device I can't see the title `Scan a Zcash Address` and the `cancel` button is now inside of the camera box. I will try in an emulator as well...

2023-03-16 01:47 UTC, fluidvanadium commented
so.... it works differently on ios and android... i may try to replace it with a newer component

2023-03-16 01:52 UTC, juanky201271 commented
> so.... it works differently on ios and android... i may try to replace it with a newer component

I didn't try yet in IOS, my testing for now is in a Android Physical device (Samsung galaxy tablet) & Android emulator (Pixel XL Android 13 SDK 33 x86_64).
But I'm sure that in Mac we have to adjust something as well.

2023-03-16 02:09 UTC, fluidvanadium commented
pre-fix on physical:

![Screenshot_20230316-020639](https://user-images.githubusercontent.com/111296437/225491354-318c59e1-f389-4a4e-9266-c0f6d0b3b9b8.png)

pre-fix on emulator

![Screenshot from 2023-03-16 02-02-36](https://user-images.githubusercontent.com/111296437/225491427-3ce12ac9-8224-4e1e-85e0-7a564f431551.png)

post-fix on emulator

![Screenshot from 2023-03-16 02-05-32](https://user-images.githubusercontent.com/111296437/225491470-16028e1c-de77-441f-8538-23f08f001707.png)

2023-03-16 02:11 UTC, fluidvanadium commented
it's clear that whatever we have isn't exactly right
why are we subtracting and dividing by constant factors instead of having the correct bounding box

i will continue to work on it

2023-03-16 02:12 UTC, fluidvanadium commented
rather than kludge the numbers, i would like to create the perfect bounding box for display on all devices. i believe the tools are there

2023-03-16 18:06 UTC, juanky201271 commented
take a look at this: https://github.com/react-native-camera/react-native-camera/issues/2388#issuecomment-520123596

`overflow` can be a good tool.

2023-03-17 01:30 UTC, fluidvanadium commented
> take a look at this: [react-native-camera/react-native-camera#2388 (comment)](https://github.com/react-native-camera/react-native-camera/issues/2388#issuecomment-520123596)

your refactor really helped me! like a catapult

okay, so i got rid of most of that file. now it works great!

2023-03-17 01:51 UTC, juanky201271 requested changes

2023-03-17 01:51 UTC, juanky201271 commented on components/Send/components/ScannerAddress.tsx
> +    <View style={{
I was testing in IOS... and you need to change this `View` to `SafeAreaView` from react-native. In Android have no effect but in IOS is important.

2023-03-17 01:56 UTC, juanky201271 requested changes

2023-03-17 01:56 UTC, juanky201271 commented on components/Send/Send.tsx
> +  console.log('render send', 'w', dimensions.width, 'h', dimensions.height);
and delete this log -> it's a little bit annoying... hehehe.

2023-03-17 21:01 UTC, closed without merging