only ask remote for chain information when necessary
zingolabs/zingo-mobile pull request #276
Opened 2023-04-05 14:54 UTC by zancas

2023-04-19 20:00 UTC, AloeareV commented on rust/lib/src/lib.rs
> +        _ => panic!("Unrecognized server URI, is it a new server?  What chain does it serve?"),
`127.0.0.1` could easily be a local testnet or mainnet server. Also, the zecwallet lightwalletd servers don't match this naming scheme, and I suspect other ones don't.

2023-04-19 20:05 UTC, zancas commented on rust/lib/src/lib.rs
> +        _ => panic!("Unrecognized server URI, is it a new server?  What chain does it serve?"),
Running on a mobile device?  I concede that it's possible, but I'm not aware of any as of yet.
What's a more comprehensive option?

2023-04-19 22:35 UTC, zancas commented on rust/lib/src/lib.rs
> +        _ => panic!("Unrecognized server URI, is it a new server?  What chain does it serve?"),
OK, this is now an explicit list of known servers that we should extend as we become aware of new ones.  Also the _caller_ of `infer_chaintype` needs to have the option to dictate chain-type.

2023-04-20 02:20 UTC, fluidvanadium commented on rust/lib/src/lib.rs
> +        _ => panic!("Unrecognized server URI, is it a new server?  What chain does it serve?"),
making a note of this as a list of targets to attack

2023-04-20 15:31 UTC, AloeareV requested changes
Looks pretty great!

2023-04-20 15:31 UTC, AloeareV commented on rust/lib/src/lib.rs
> +    };
Let's get rid of this unwrap:
```suggestion
    let chaintype = match chain_type {
        Some(chaintype) => chaintype,
        None => infer_chaintype(&lightwalletd_uri.to_string()),
    };
```

2023-04-20 16:03 UTC, AloeareV submitted a review, later dismissed

2023-04-20 16:19 UTC, juanky201271 requested changes

2023-04-20 16:19 UTC, juanky201271 commented on rust/lib/src/lib.rs
> +        | "https://lwdv3.zecwallet.co" => ChainType::Mainnet,
we should put here the port `:443`, otherwise it doesn't match.

2023-04-20 16:43 UTC, zancas commented
@juanky201271 the version that's in place as I write this addresses both of the issues you noticed today:

* field rename data_dir --> zingo_wallet_dir
* missing port number

2023-04-20 17:06 UTC, juanky201271 approved these changes, later dismissed

2023-04-20 17:55 UTC, zancas commented
Hi @Oscar-Pepper and @fluidvanadium we're not able to merge this, which is necessary to sync `zingolib` - `zingo-mobile`, because of the failing required CI tests.

2023-04-20 19:02 UTC, fluidvanadium commented
```
yarn react-native run-android
yarn run v1.22.19
$ /home/sava/ZINGO/testing2/node_modules/.bin/react-native run-android
info Starting JS server...
info Installing the app...

> Configure project :app
WARNING: The Gradle Managed Device DSL and associated tests are experimental

> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/home/sava/ZINGO/testing2/node_modules/react-native-reanimated/android/react-native-reanimated-70-hermes.aar

> Task :app:installDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
301 actionable tasks: 3 executed, 298 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No connected devices!

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s

error Failed to install the app. Make sure you have an Android emulator running or a device connected.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No connected devices!

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s

    at makeError (/home/sava/ZINGO/testing2/node_modules/execa/index.js:174:9)
    at /home/sava/ZINGO/testing2/node_modules/execa/index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (/home/sava/ZINGO/testing2/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/home/sava/ZINGO/testing2/node_modules/@react-native-community/cli/build/index.js:142:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2023-04-20 19:07 UTC, fluidvanadium commented
im not able to run it. here's a different error i got:
```
yarn react-native run-android
yarn run v1.22.19
$ /home/sava/ZINGO/testing2/node_modules/.bin/react-native run-android
info Starting JS server...
info Launching emulator...
info Successfully launched emulator.
info Installing the app...

> Configure project :app
WARNING: The Gradle Managed Device DSL and associated tests are experimental

> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/home/sava/ZINGO/testing2/node_modules/react-native-reanimated/android/react-native-reanimated-70-hermes.aar

> Task :app:installDebug
Installing APK 'app-debug.apk' on '30_ga_32(AVD) - 11' for :app:debug

> Task :app:installDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
301 actionable tasks: 3 executed, 298 up-to-date
Unable to install /home/sava/ZINGO/testing2/android/app/build/outputs/apk/debug/app-debug.apk
com.android.ddmlib.InstallException: Unknown failure: Exception occurred while executing 'install':
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.pm.PackageManagerInternal.freeStorage(java.lang.String, long, int)' on a null object reference
at com.android.server.StorageManagerService.allocateBytes(StorageManagerService.java:3901)
at android.os.storage.StorageManager.allocateBytes(StorageManager.java:2278)
at android.os.storage.StorageManager.allocateBytes(StorageManager.java:2335)
at com.android.server.pm.PackageInstallerSession.doWriteInternal(PackageInstallerSession.java:987)
at com.android.server.pm.PackageInstallerSession.write(PackageInstallerSession.java:940)
at android.content.pm.PackageInstaller$Session.write(PackageInstaller.java:1041)
at com.android.server.pm.PackageManagerShellCommand.doWriteSplit(PackageManagerShellCommand.java:3269)
at com.android.server.pm.PackageManagerShellCommand.doWriteSplits(PackageManagerShellCommand.java:3231)
at com.android.server.pm.PackageManagerShellCommand.doRunInstall(PackageManagerShellCommand.java:1296)
at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1248)
at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:184)
at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
at android.os.ShellCommand.exec(ShellCommand.java:44)
at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21648)
at android.os.Binder.shellCommand(Binder.java:929)
at android.os.Binder.onTransact(Binder.java:813)
at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4603)
at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4305)
at android.os.Binder.execTransactInternal(Binder.java:1159)
at android.os.Binder.execTransact(Binder.java:1123)
        at com.android.ddmlib.internal.DeviceImpl.installRemotePackage(DeviceImpl.java:1315)
        at com.android.ddmlib.internal.DeviceImpl.installPackage(DeviceImpl.java:1141)
        at com.android.ddmlib.internal.DeviceImpl.installPackage(DeviceImpl.java:1117)
        at com.android.ddmlib.internal.DeviceImpl.installPackage(DeviceImpl.java:1106)
        at com.android.build.gradle.internal.testing.ConnectedDevice.installPackage(ConnectedDevice.java:127)
        at com.android.build.gradle.internal.tasks.InstallVariantTask.install(InstallVariantTask.java:162)
        at com.android.build.gradle.internal.tasks.InstallVariantTask.lambda$doTaskAction$1(InstallVariantTask.java:99)
        at com.android.builder.testing.api.DeviceProvider.use(DeviceProvider.java:53)
        at com.android.build.gradle.internal.tasks.InstallVariantTask.doTaskAction(InstallVariantTask.java:94)
        at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(BaseTask.kt:66)
        at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:51)
        at com.android.build.gradle.internal.tasks.NonIncrementalTask.taskAction(NonIncrementalTask.kt:97)
        at jdk.internal.reflect.GeneratedMethodAccessor1067.invoke(Unknown Source)
        at java.base@11.0.18/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@11.0.18/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.TaskExecution$2.run(TaskExecution.java:239)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:224)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:207)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:190)
        at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:168)
        at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:89)
        at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:40)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:53)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:50)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:50)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:40)
        [...]

2023-04-21 05:53 UTC, fluidvanadium commented
oh, i see 3/4 integration tests passing in ci, 3/4 e2e tests passing in ci, 3/4 e2e tests passing locally

2023-04-21 13:47 UTC, juanky201271 requested changes

2023-04-21 13:47 UTC, juanky201271 commented on rust/lib/src/lib.rs
> +        x if x.contains("127.0.0.1") | x.contains("localhost") => ChainType::Regtest,
Just in case... you have to put the `/` slash at the end of all of the URI's... otherwise it will fail

2023-04-21 15:21 UTC, zancas commented
I am moving this back to draft..  it's a larger change than necessary to sync zingo-mobile and zingolib.

2023-07-18 10:23 UTC, juanky201271 commented
I think we can close this old PR safely, since we include the chain_type selection in the UI.
@zancas feel free to reopen this if needed.

2023-07-18 10:23 UTC, closed without merging