modularized emulator scripts.
zingolabs/zingo-mobile pull request #366
Opened 2023-05-25 19:46 UTC by fluidvanadium

this was needed because a couple steps in the process are flaky, and it was no good to rerun the whole process. this brings DRY readability improvements as well as efficiency. should be able run ./scripts/start_flow_emulate.sh with an abi (-a, they all work) and get a very easy path to running the app. if things go wrong, simply read start_flow_emulate.sh, there are two nested layers of control. running ./scripts/flow_emulator_run_apk.sh restarts it if closed without repeating the setup work.

2023-05-26 14:30 UTC, Oscar-Pepper requested changes
we need to add snapshot back into this i think. but lets do that in a new PR!

2023-05-26 14:30 UTC, Oscar-Pepper commented on .detoxrc.js
can we put e2e stuff in a new PR?

2023-05-26 14:30 UTC, Oscar-Pepper commented on e2e/load.test.js
can we put e2e stuff in a new PR?

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/emulator_run.sh
> +source ./scripts/emulator_read_target.sh
love it

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/start_flow_emulate.sh
> +./scripts/build_apk.sh
i thought this was in my PR but can we put build_apk at the top please?

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/emulator_run.sh
> +emulator -avd "${avd_name}" -netdelay none -netspeed full -no-boot-anim -no-snapshot-save -read-only -port 5554 |& tee "${output_dir}/emulator_run.txt" &
i dont like the emulator stuff printing to console... can we clean this up by replacing tee with &> ? thanks

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/build_apk.sh
> +echo ""
even better than blank echo... lets put `echo "\nBuilding native rust..."

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/build_apk.sh
> +./build.sh
there is no errors/protection from calling this script from wrong directory

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/build_apk.sh
> +./build.sh
`git rev-parse --show-toplevel` is a much better solution to this than creating errors when we are no in the root directory (which i did in my scripts before i found this little nugget)

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/build_apk.sh
> +cd android
use `git rev-parse --show-toplevel` to set up path here too

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/emulator_create.sh
> +source ./scripts/emulator_read_target.sh
use git rev-parse --show-toplevel to set up path here too

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/emulator_dependencies.sh
> +source ./scripts/emulator_read_target.sh
use git rev-parse --show-toplevel to set up path here too

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/emulator_install_apk.sh
> +source ./scripts/emulator_read_target.sh
use git rev-parse --show-toplevel to set up path here too

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/emulator_install_apk.sh
> +        echo "For more information see 'android/${test_report_dir}/apk_installation.txt'" >&2
random `test_report_dir` in here

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/emulator_install_apk.sh
> +    if adb -s emulator-5554 install -r -t -d --abi "${abi}" "android/app/build/outputs/apk/debug/app-${abi}-debug.apk" |& tee "${output_dir}/emulator_install_apk.txt"; then
path could be wrong if script is not run from root directory. solve with `git rev-parse --show-toplevel` or error if not in root

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/emulator_launch_app.sh
> +source ./scripts/emulator_read_target.sh
path could be wrong if script is not run from root directory. solve with `git rev-parse --show-toplevel` or error if not in root

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/emulator_launch_app.sh
> +    metro_status=$(cat ./${output_dir}/react-native_start.txt | grep Metro)
path could be wrong if script is not run from root directory. solve with `git rev-parse --show-toplevel` or error if not in root

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/emulator_launch_app.sh
> +adb -s emulator-5554 shell logcat -v threadtime -b main &> "${output_dir}/logcat.txt" &
path could be wrong if script is not run from root directory. solve with `git rev-parse --show-toplevel` or error if not in root

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/emulator_launch_app.sh
> +adb -s emulator-5554 shell logcat -v threadtime -b main &> "${output_dir}/logcat.txt" &
maybe `output_dir` could be changed to be an absolute path that includes `git rev-parse --show-toplevel` which would solve a lot of these problems with path errors

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/emulator_launch_app.sh
> +nohup yarn react-native start &> "${output_dir}/react-native_start.txt" &
ok not pointing out any more paths as lots of clutter! ALL THE PATHS :D

2023-05-26 14:30 UTC, Oscar-Pepper commented on scripts/emulator_read_target.sh
> +output_dir="android/app/build/outputs/emulator_output"
if we make this an absolute path with `git rev-parse --show-toplevel` then everything that uses `output_dir` is protected from running in wrong directory... however be careful to remove the `./` from paths in the code with `./${output_dir}/foo/bar`

2023-05-26 15:33 UTC, fluidvanadium commented on scripts/start_flow_emulate.sh
> +./scripts/build_apk.sh
the reason i switched it back is to fail immediately if -a is unrecognized

2023-05-26 18:36 UTC, Oscar-Pepper commented on scripts/start_flow_emulate.sh
> +./scripts/build_apk.sh
ok good

2023-05-28 11:51 UTC, Oscar-Pepper approved these changes
Really great job!

2023-05-28 11:51 UTC, Oscar-Pepper commented on scripts/build_apk.sh
> +echo "/nBuilding native rust..."
sorry my bad this needs a `-e` flag to process the `\n` like this:
`echo -e "\nBuilding native rust..."`

2023-05-28 11:51 UTC, Oscar-Pepper commented on scripts/emulator_install_apk.sh
> +        echo "For more information see '${output}/apk_installation.txt'" >&2
this needs to be the file created on install (line 10)
`${output_dir}/emulator_install_apk.txt`

2023-05-28 11:51 UTC, Oscar-Pepper commented on scripts/emulator_install_apk.sh
> +        echo "For more information see '${output}/apk_installation.txt'" >&2
you can set the 100 to 0 to test what happens when it fails

2023-05-28 11:53 UTC, merged