e2e test testnet
zingolabs/zingo-mobile pull request #431
Opened 2023-07-05 21:26 UTC by fluidvanadium

right now, this test downloads the main chain from the testnet server.

2023-07-06 18:39 UTC, juanky201271 requested changes

2023-07-06 18:39 UTC, juanky201271 commented on e2e/loadTestnetWallet.js
> +  await element(by.id('menu.settings')).tap();
I would put a `waitfor` before this line Just in case...

2023-07-06 18:39 UTC, juanky201271 commented on e2e/loadTestnetWallet.js
> +  await element(by.id("settings.customServerField")).replaceText('https://testnet.lightwalletd.com');
you don't need to do this twice... I guess.

2023-07-06 18:39 UTC, juanky201271 commented on e2e/loadTestnetWallet.js
> +
Before you save the setting you need to `tap` on `testnet` in the Chain Toggle component.

2023-07-10 06:29 UTC, juanky201271 requested changes

2023-07-10 06:29 UTC, juanky201271 commented on components/Components/ChainTypeToggle.tsx
> +      <TouchableOpacity testID="settings.chaintype.test" style={{ marginHorizontal: 5 }} onPress={() => onPress('test')}>
I don't think it is appropriate to use `settings` here since this component is called from other components, Settings & AppLoading

2023-07-10 06:29 UTC, juanky201271 commented on e2e/testnet_wallet.test.js
> +  await element(by.id('settings.scrollView')).scroll(1000, 'down');
Maybe I'm a pain... but I would put before a `waitfor` line... for `settings.scrollView`

2023-07-10 06:29 UTC, juanky201271 commented on e2e/testnet_wallet.test.js
> +  await element(by.id("settings.chaintype.test")).tap();
`waitfor` as well.

2023-07-10 06:29 UTC, juanky201271 commented on e2e/testnet_wallet.test.js
> +  await element(by.id('settings.button.save')).tap();
`waitfor` too.

2023-07-10 06:50 UTC, juanky201271 requested changes

2023-07-10 06:50 UTC, juanky201271 commented on e2e/testnet_wallet.test.js
> +let sendTestnet = async () => {
`sendTestnet` is never used it and it is a copy of `syncTestnet`, I don't know what is for...

2023-07-10 06:50 UTC, juanky201271 commented on e2e/testnet_wallet.test.js
> +    // await element(by.id('send.checkboxUA')).tap();
You need this line to include in the `memo` file the UA, otherwise this test will fail always.

2023-07-10 06:50 UTC, juanky201271 commented on e2e/testnet_wallet.test.js
> +      '1\n2\n3\n4\n5\n6\n7\n8\nReply to: \nutest1kcth7yst8s7u4yqf9hnrrfmrte40sy49z83qctvmxc528xf37swhkw53yhhzmceq07a83waevggwh3uyxffjgx30wcua2s0rgpt3seeae4nlrdedj9kxdgcx9uyug3d0ae5rk4q22r8pl37h75pnfa
Here you are expecting 8 lines with the numbers... but you put in this field the value `8008`... I don't understand it, maybe I'm missing something.

2023-07-10 07:00 UTC, juanky201271 requested changes, later dismissed

2023-07-10 07:00 UTC, juanky201271 commented on e2e/testnet_wallet.test.js
> +  it('adds return address to the memo if that option is selected, and correctly renders confirm screen', async () => {
I would use here `waitfor` for all the lines with `element`, just in case...

2023-07-10 07:00 UTC, juanky201271 commented on e2e/testnet_wallet.test.js
> +    await element(by.id('send.memo-field')).replaceText("8008");
I think you need to put here this value: "1\n2\n3\n4\n5\n6\n7\n8".

2023-07-10 07:00 UTC, juanky201271 commented on e2e/testnet_wallet.test.js
> +  }
You need to close this screen (sync report) here before this test continue.

2023-07-10 07:00 UTC, juanky201271 commented on e2e/testnet_wallet.test.js
> +  await element(by.text('CLOSE')).tap;
you need to copy this line at the end of `syncTestnet`.

2023-07-13 20:16 UTC, fluidvanadium commented
okay @juanky201271, this is not ready to merge. i have a couple issues into which you you may have insight:
testnet_wallet.test.js
line 72: doesnt seem to catch when sync is finished, even though "Finished" comes on the screen.
line 129: doesnt match the send all enabler. im totally confused about what the testID could be

2023-07-13 21:38 UTC, juanky201271 requested changes

2023-07-13 21:38 UTC, juanky201271 commented on components/Components/ChainTypeToggle.tsx
> +      <TouchableOpacity testID="chaintype.testnet" style={{ marginHorizontal: 5 }} onPress={() => onPress('test')}>
You need to run `yarn test -u` and update the snapshots...

2023-07-13 21:48 UTC, juanky201271 requested changes

2023-07-13 21:48 UTC, juanky201271 commented on e2e/testnet_wallet.test.js
> +  await waitFor(element(by.text("Finished"))).toBeVisible().withTimeout(sync_timeout)
Maybe 10 seconds for `background_duration` is not enough, just an idea, try to make this bigger...

2023-07-13 21:48 UTC, juanky201271 commented on e2e/testnet_wallet.test.js
> +  await waitFor(element(by.id('settings.sendalls-enable'))).toBeVisible().withTimeout(ui_timeout);
I think the `TestID` is correct, but you need to scroll a little bit first to find this field.

2023-07-14 12:38 UTC, juanky201271 submitted a review, later dismissed

2023-07-14 13:25 UTC, juanky201271 commented
I did my best, in my local all of the e2e tests are working... @fluidvanadium check it out, when you have a chance.

2023-07-28 21:32 UTC, juanky201271 commented
@fluidvanadium I resolved the conflicts, It's ready for checking it out.

2023-11-08 18:15 UTC, juanky201271 commented
@fluidvanadium @Oscar-Pepper I still think this PR is useful, maybe we need to adapt something, what do you think? otherwise I'm going to close it.

2023-11-18 15:45 UTC, Oscar-Pepper commented
i am personally in favour of using the new regtest framework instead of testnet, as testnet tests will eventually get unreasonably long to run when anything useful is involved like syncing or sending. i am closing this and porting our tests to run in a regtest network

2023-11-18 15:45 UTC, closed without merging