Native Alerts instead red buttons
zingolabs/zingo-mobile pull request #468
Opened 2023-07-27 23:34 UTC by juanky201271

* red fetch price button -> Alert.
* red confirm button in seed screen -> Alert.
* red confirm button in ufvk screen -> Alert.

2023-07-28 16:53 UTC, Oscar-Pepper commented
wow looks really good! i think the alerts should match in style and maybe could be worded a bit better i will add comments in my review

2023-07-28 16:56 UTC, juanky201271 commented
> wow looks really good! i think the alerts should match in style and maybe could be worded a bit better i will add comments in my review

of course,,, I'm waiting for the new design to create a new custom component to replace the white and ugly alerts... https://github.com/zingolabs/zingo-mobile/issues/469

2023-07-28 17:00 UTC, Oscar-Pepper requested changes
i think its looks best to have lower case in the alert to match the fetch USD alert...
can we change here also? https://github.com/zingolabs/zingo-mobile/pull/468/files#diff-c2ea5ebbb49266a16477e2cf76c9fa904d1faadbd317f92ccc6914874222b7cfR259

2023-07-28 17:00 UTC, Oscar-Pepper commented on app/translations/en.json
> +        "Are you sure 100% or more"
this should read:

Are you 100% sure?

2023-07-28 17:00 UTC, Oscar-Pepper commented on app/translations/en.json
> +        "Are you sure 100% or more"
this should read:

Are you 100% sure?

2023-07-28 17:00 UTC, Oscar-Pepper commented on app/translations/en.json
> +        "Are you sure 100% or more"
this should read:

Are you 100% sure?

2023-07-28 17:00 UTC, Oscar-Pepper commented on app/translations/en.json
> +        "Are you sure 100% or more"
this should read:

Are you 100% sure?

2023-07-28 17:00 UTC, Oscar-Pepper commented on app/translations/en.json
> +        "Are you sure 100% or more"
this should read:

Are you 100% sure?

2023-07-28 17:00 UTC, Oscar-Pepper commented on app/translations/en.json
> +        "Are you sure 100% or more"
this should read:

Are you 100% sure?

2023-07-28 17:00 UTC, Oscar-Pepper commented on app/translations/en.json
> +    "server-warning": "IF YOU CHANGE TO A SERVER WITH A DIFFERENT CHAIN, YOU WILL NO LONGER BE ABLE TO VIEW THIS WALLET WITHOUT THE VIEWING KEY",
to match the other alert this should not be capitals and i think it looks better smaller in the alert:

"If you change to a server with a different chain, you will no longer be able to view this wallet without the viewing key"

2023-07-28 17:00 UTC, Oscar-Pepper commented on app/translations/es.json
> +    "server-warning": "SI CAMBIAS A UN SERVIDOR CON DIFERENTE TIPO DE CADENA, YA NO PODRAS VER ESTE MONEDERO SIN LA CLAVE DE VISUALIZACION.",
i think lower case letters looks better for this alert

2023-07-28 18:58 UTC, zancas commented
I assume @Oscar-Pepper will merge this one when he's satisfied.

2023-07-29 08:48 UTC, Oscar-Pepper requested changes
Just need to change 'see' to 'seed' and good to go! See my comment

2023-07-29 08:48 UTC, Oscar-Pepper commented on app/translations/en.json
> +    "change-warning": "If you change to another wallet, you will no longer have access to this wallet without the see phrase.",
All of these say 'see' instead of 'seed'

2023-07-29 20:10 UTC, juanky201271 commented
> Just need to change 'see' to 'seed' and good to go! See my comment

fixed!

2023-07-31 16:02 UTC, zancas requested changes
In the English version lets change `100%` to `certain`, I am not clear on how to change it in Spanish.

2023-07-31 16:02 UTC, zancas commented on app/translations/en.json
> +        "Are you 100% sure?"
I vote we change this to:   `Are you certain?`

2023-07-31 16:02 UTC, zancas commented on app/translations/en.json
> +    "fetchpricebody": "Please confirm that you want to fetch the USD price from internet.",
"from internet"  -->  "from the internet"

2023-07-31 16:02 UTC, zancas commented on app/translations/en.json
> +    "needtoshield": "Have funds to shield",
"You have funds to shield."

2023-07-31 16:15 UTC, juanky201271 commented
> In the English version lets change `100%` to `certain`, I am not clear on how to change it in Spanish.

in Spanish can be: `Estas seguro/a?`... I made all of suggestions... @zancas

2023-08-01 14:19 UTC, Oscar-Pepper approved these changes

2023-08-01 17:10 UTC, zancas approved these changes

2023-08-01 17:10 UTC, merged