Translations
zingolabs/zingo-mobile pull request #682
Opened 2024-08-20 22:55 UTC by nachog00

- Added translations of readme and pricacy polixy in:
  - spanish
  - geman
  - turkish

- Left original file privacy_policy.txt unchanged as we didnt know if it was being read somewhere on the code.

2024-08-21 00:03 UTC, juanky201271 commented
Probably the privacy policy TXT can be removed. 
I think would be a good idea if in each readme we have a link to the new privacy policy MD, IDK maybe at the end, after the troubleshooting section...
@zancas what do you think?

2024-08-21 00:07 UTC, juanky201271 requested changes
Probably the privacy policy TXT can be removed.
I think would be a good idea if in each readme we have a link to the new privacy policy MD, IDK maybe at the end, after the troubleshooting section...
@zancas what do you think?

2024-08-21 01:34 UTC, nachog00 commented
Just noticed, there are some missing sections from the original README on the translations.
Also, forgot to add the troubleshooting translations.

2024-09-18 16:52 UTC, zancas commented
Go with @juanky201271 's suggestion.

2025-03-15 18:59 UTC, juanky201271 commented
@nachog00 please let us know what is your plan with this...

2025-03-25 18:56 UTC, zancas commented
@nachog00 can you circle back to this?

2025-05-11 13:19 UTC, zancas commented
@nachog00 ?

2025-05-19 20:00 UTC, zancas commented
@nachog00 can you update this or close it?

2025-05-19 20:12 UTC, closed without merging