Add TEX parsing integration tests
zingolabs/zingo-mobile pull request #726
Opened 2024-10-11 23:53 UTC by dorianvp

This PR adds an integration test which tries to parse 2 TEX addresses, a correct one and a random string.

2024-10-11 23:59 UTC, dorianvp commented
Now that I think about it, maybe we should move the **wrong** parsing to another separate function, and create functions for parsing on each network. What do you think @juanky201271 ?

2024-10-12 02:54 UTC, juanky201271 requested changes

2024-10-12 02:54 UTC, juanky201271 commented on android/app/src/androidTest/java/org/ZingoLabs/Zingo/RustFFITest.kt
> +        assertThat(initFromSeed.birthday).isEqualTo(1)
For clarity here I would use the vars: seed & birthday...

2024-10-12 02:54 UTC, juanky201271 commented on android/app/src/androidTest/java/org/ZingoLabs/Zingo/RustFFITest.kt
> +        assertThat(result).isNotNull()
Take a look at this:
https://github.com/zingolabs/zingo-mobile/blob/0888420b39079f0fe5ce3617fef1f092d5c8eae6/app/utils/Utils.ts#L310
The result of this command is a bit weird... you can have a `null` string, or an string beginning by `Error`, or a valid JSON object with the field `success` with value `success` and chain_name... this validation is a bit complex...

2024-10-12 02:57 UTC, juanky201271 commented
> Now that I think about it, maybe we should move the **wrong** parsing to another separate function, and create functions for parsing on each network. What do you think @juanky201271 ?

IMO to have 4 separate tests would be the best option. I think we have to use `regtest` as much as we can and don't realy in any external servers. And, please put those 4 tests in CI if you can. Thanks, good job.

2024-10-15 21:12 UTC, juanky201271 requested changes

2024-10-15 21:12 UTC, juanky201271 commented on rust/zingomobile_utils/src/lib.rs
> -
You need to put this back, because is to run the tests in mac.

2024-10-16 03:15 UTC, juanky201271 approved these changes, later dismissed

2024-10-16 14:54 UTC, juanky201271 approved these changes
This is nice.

2024-10-16 14:55 UTC, merged