Update zingolib version for new scenario
zingolabs/zingo-mobile pull request #745
Opened 2024-11-02 19:46 UTC by dorianvp

2024-11-02 22:23 UTC, juanky201271 requested changes

2024-11-02 22:23 UTC, juanky201271 commented on rust/Cargo.toml
> +zingolib = { git = "https://github.com/zingolabs/zingolib", default-features = true, rev = "cab1ca5b99120bee291d67f37f325715679b29fb", features = [
I'm thinking about to put a specific commit... but IMO is better to put the `dev` branch... and sometimes to update the Cargo.lock after a `cargo update....` when is necessary.

2024-11-02 22:23 UTC, juanky201271 commented on rust/android/Cargo.toml
> +darkside-tests = { git = "https://github.com/zingolabs/zingolib", default-features = true, rev = "cab1ca5b99120bee291d67f37f325715679b29fb" }
same here...

2024-11-03 19:24 UTC, dorianvp commented
I am converting this PR back to draft. Somehow the zingolib update (both this commit and the latest one in the dev branch) broke sync for me with the following logs:
```Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.ZingoLabs.Zingo/.MainActivity }
 BUNDLE  ./index.js 

 LOG  Running "Zingo" with {"rootTag":11}
 LOG  false undefined BIOMETRIC_ERROR_NONE_ENROLLED
 LOG  crypto provider result true
 LOG  stop sync process. STOPPED
 LOG  Critical Error addresses balances notes SyntaxError: JSON Parse error: Unexpected character: s
 LOG  stop sync process. STOPPED
 LOG  Critical Error addresses balances notes SyntaxError: JSON Parse error: Unexpected character: s
 LOG  stop sync process. STOPPED
 LOG  Critical Error addresses balances notes SyntaxError: JSON Parse error: Unexpected character: s
 LOG  stop sync process. STOPPED
 LOG  RPC - Update Data lock, returning *****************************
 LOG  REFRESH ----> in refresh is true
 LOG  REFRESH ----> in refresh is true
 LOG  sync finished {
  "result": "success",
  "latest_block": 2703851,
  "total_blocks_synced": 1
}
 LOG  REFRESH ----> in refresh is true
 LOG  ++++++++++ interval update 5 secs [84, 85, 224]
 LOG  Critical Error addresses balances notes SyntaxError: JSON Parse error: Unexpected character: s
 LOG  stop sync process. STOPPED
 LOG  RPC - Update Data lock, returning *****************************
```

2024-11-03 19:27 UTC, juanky201271 commented
> I am converting this PR back to draft. Somehow the zingolib update (both this commit and the latest one in the dev branch) broke sync for me with the following logs:
> 
> ```
>  BUNDLE  ./index.js 
> 
>  LOG  Running "Zingo" with {"rootTag":11}
>  LOG  false undefined BIOMETRIC_ERROR_NONE_ENROLLED
>  LOG  crypto provider result true
>  LOG  stop sync process. STOPPED
>  LOG  Critical Error addresses balances notes SyntaxError: JSON Parse error: Unexpected character: s
>  LOG  stop sync process. STOPPED
>  LOG  Critical Error addresses balances notes SyntaxError: JSON Parse error: Unexpected character: s
>  LOG  stop sync process. STOPPED
>  LOG  Critical Error addresses balances notes SyntaxError: JSON Parse error: Unexpected character: s
>  LOG  stop sync process. STOPPED
>  LOG  RPC - Update Data lock, returning *****************************
>  LOG  REFRESH ----> in refresh is true
>  LOG  REFRESH ----> in refresh is true
>  LOG  sync finished {
>   "result": "success",
>   "latest_block": 2703851,
>   "total_blocks_synced": 1
> }
>  LOG  REFRESH ----> in refresh is true
>  LOG  ++++++++++ interval update 5 secs [84, 85, 224]
>  LOG  Critical Error addresses balances notes SyntaxError: JSON Parse error: Unexpected character: s
>  LOG  stop sync process. STOPPED
>  LOG  RPC - Update Data lock, returning *****************************
> ```
> 
> This also breaks some detox tests.

this is the problem... https://github.com/zingolabs/zingolib/issues/1485 the command balance changed and now it is not a valid string JSON...

2024-11-04 19:31 UTC, juanky201271 approved these changes
good job.

2024-11-04 19:31 UTC, merged