update Cargo.lock, which picks up latest zingolib/dev
zingolabs/zingo-mobile pull request #94
Opened 2022-07-12 16:53 UTC by zancas

When I try to build against this branch, I don't see the `ZingoConfig`-vs-`LightClientConfig` errors I had expected but I do see some `Orchard`-related errors:

```
cargo build
warning: Patch `bellman v0.13.0 (https://github.com/zingolabs/bellman?rev=712337ea591cb89e031b9f203462d32de00bf7ff#712337ea)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
   Compiling zingolib v0.1.1 (https://github.com/zingolabs/zingolib?branch=dev#e8677475)
error[E0277]: the trait bound `Action<_>: ShieldedOutput<_, 580_usize>` is not satisfied
   --> /home/mherder/.cargo/git/checkouts/zingolib-2003bc87acd6fa69/e867747/lib/src/blaze/fetch_full_transaction.rs:570:9
    |
570 |         scan_bundle(
    |         ^^^^^^^^^^^ the trait `ShieldedOutput<_, 580_usize>` is not implemented for `Action<_>`
    |
note: required by a bound in `scan_bundle`
   --> /home/mherder/.cargo/git/checkouts/zingolib-2003bc87acd6fa69/e867747/lib/src/blaze/fetch_full_transaction.rs:611:8
    |
591 | async fn scan_bundle<K, B, L, O, D, E>(
    |          ----------- required by a bound in this
...
611 |     O: ShieldedOutput<D, ENC_CIPHERTEXT_SIZE>,
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `scan_bundle`

error[E0277]: the trait bound `OrchardDomain: Domain` is not satisfied
   --> /home/mherder/.cargo/git/checkouts/zingolib-2003bc87acd6fa69/e867747/lib/src/blaze/fetch_full_transaction.rs:570:9
    |
570 |         scan_bundle(
    |         ^^^^^^^^^^^ the trait `Domain` is not implemented for `OrchardDomain`
    |
note: required by a bound in `scan_bundle`
   --> /home/mherder/.cargo/git/checkouts/zingolib-2003bc87acd6fa69/e867747/lib/src/blaze/fetch_full_transaction.rs:610:8
    |
591 | async fn scan_bundle<K, B, L, O, D, E>(
    |          ----------- required by a bound in this
...
610 |     D: Domain,
    |        ^^^^^^ required by this bound in `scan_bundle`

error[E0277]: the trait bound `OrchardDomain: Domain` is not satisfied
   --> /home/mherder/.cargo/git/checkouts/zingolib-2003bc87acd6fa69/e867747/lib/src/blaze/trial_decryptions.rs:234:33
    |
233 | ...                   zcash_note_encryption::try_compact_note_decryption(
    |                       -------------------------------------------------- required by a bound introduced by this call
234 | ...                       &OrchardDomain::for_nullifier(action.nullifier()),
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Domain` is not implemented for `OrchardDomain`
    |
note: required by a bound in `zcash_note_encryption::try_compact_note_decryption`
   --> /home/mherder/.cargo/git/checkouts/librustzcash-0a74bd38a00f78b0/37fc286/components/zcash_note_encryption/src/lib.rs:609:39
    |
609 | pub fn try_compact_note_decryption<D: Domain, Output: ShieldedOutput<D, COMPACT_NOTE_SIZE>>(
    |                                       ^^^^^^ required by this bound in `zcash_note_encryption::try_compact_note_decryption`

error[E0277]: the trait bound `CompactAction: ShieldedOutput<OrchardDomain, 52_usize>` is not satisfied
   --> /home/mherder/.cargo/git/checkouts/zingolib-2003bc87acd6fa69/e867747/lib/src/blaze/trial_decryptions.rs:236:33
    |
233 | ...                   zcash_note_encryption::try_compact_note_decryption(
    |                       -------------------------------------------------- required by a bound introduced by this call
...
236 | ...                       &action,
    |                           ^^^^^^^ the trait `ShieldedOutput<OrchardDomain, 52_usize>` is not implemented for `CompactAction`
    |
note: required by a bound in `zcash_note_encryption::try_compact_note_decryption`
   --> /home/mherder/.cargo/git/checkouts/librustzcash-0a74bd38a00f78b0/37fc286/components/zcash_note_encryption/src/lib.rs:609:55
    |
609 | pub fn try_compact_note_decryption<D: Domain, Output: ShieldedOutput<D, COMPACT_NOTE_SIZE>>(
    |                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `zcash_note_encryption::try_compact_note_decryption`

error[E0277]: the trait bound `OrchardDomain: Domain` is not satisfied
   --> /home/mherder/.cargo/git/checkouts/zingolib-2003bc87acd6fa69/e867747/lib/src/blaze/trial_decryptions.rs:235:33
    |
235 | ...                   &ivk,
    |                       ^^^^ the trait `Domain` is not implemented for `OrchardDomain`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `zingolib` due to 5 previous errors
```

2022-07-12 17:03 UTC, AloeareV commented
See #95

2022-07-12 18:09 UTC, zancas commented
I believe that the current version of this feature, allows `zingo-mobile` to build.

2022-07-12 20:34 UTC, juanky201271 requested changes
ERROR:
#48 62.92    Compiling pairing v0.22.0
#48 62.99    Compiling pasta_curves v0.4.0
#48 63.68    Compiling tokio-util v0.7.3
#48 65.16    Compiling tokio-io-timeout v1.2.0
#48 65.40    Compiling tokio-rustls v0.23.4
#48 65.55    Compiling tokio-stream v0.1.9
#48 65.69    Compiling bls12_381 v0.7.0
#48 65.88    Compiling halo2_proofs v0.2.0
#48 66.07    Compiling bellman v0.13.1
#48 66.44    Compiling h2 v0.3.13
#48 66.97 error[E0599]: `rayon::range::Iter<u32>` is not an iterator
#48 66.97    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bellman-0.13.1/src/multiexp.rs:290:10
#48 66.97     |
#48 66.97 290 |         .step_by(c as usize)
#48 66.97     |          ^^^^^^^ `rayon::range::Iter<u32>` is not an iterator
#48 66.97     |
#48 66.97    ::: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.3/src/range.rs:48:1
#48 66.97     |
#48 66.97 48  | pub struct Iter<T> {
#48 66.97     | ------------------ doesn't satisfy `rayon::range::Iter<u32>: Iterator`
#48 66.97     |
#48 66.97     = note: the following trait bounds were not satisfied:
#48 66.97             `rayon::range::Iter<u32>: Iterator`
#48 66.97             which is required by `&mut rayon::range::Iter<u32>: Iterator`
#48 66.97 help: one of the expressions' fields has a method of the same name
#48 66.97     |
#48 66.97 290 |         .range.step_by(c as usize)
#48 66.97     |          ++++++
#48 66.97
#48 67.01 For more information about this error, try `rustc --explain E0599`.
#48 67.01 error: could not compile `bellman` due to previous error
#48 67.01 warning: build failed, waiting for other jobs to finish...
------
executor failed running [/bin/sh -c AR=llvm-ar LD=ld RANLIB=llvm-ranlib CC=x86_64-linux-android30-clang     OPENSSL_DIR=/opt/openssl-3.0.1/x86_64 cargo +nightly build -Z build-std     --target x86_64-linux-android --release]: exit code: 101

2022-07-12 20:49 UTC, zancas commented
Hmm..   checking..  that looks like the bug we patched `bellman` to fix..

2022-07-12 21:00 UTC, zancas commented
This error mentions `bellman 0.13.1`, but the patch here:

```
cargo build
warning: Patch `bellman v0.13.0 (https://github.com/zingolabs/bellman?rev=712337ea591cb89e031b9f203462d32de00bf7ff#712337ea)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
```

Mentions `bellman 0.13.0`.

I am wondering if the build is using a different "highest level" `Cargo.toml` manifest, and that's skipping the patch.

2022-07-12 21:03 UTC, juanky201271 commented
Maybe I need to run `cargo update` first??????

2022-07-13 20:18 UTC, zancas commented on rust/Cargo.toml
I added these patch directives.  It seems like the `bellman` patch is now not affecting the dependency graph!

2022-07-14 20:15 UTC, zancas commented on rust/Cargo.toml
Fixed locally.

2022-07-14 20:17 UTC, zancas commented
Hi @juanky201271 when I run:

`cd rust && build.sh`

locally, it runs to completion.

Does it work for you locally?

2022-07-14 20:52 UTC, juanky201271 approved these changes
The building works perfectly.

2022-07-14 20:52 UTC, merged